import { Prisma } from "@prisma/client";

function getRelativeDateString({ days, hours }: { days: number, hours: number }): string {
    const now = new Date();
    now.setDate(now.getDate() + days);
    now.setHours(now.getHours() + hours);
    return now.toISOString();
}

export const shifts: Prisma.ShiftCreateInput[] = [
  {
      startAt: getRelativeDateString({ days: -120, hours: 7 }),
      endAt: getRelativeDateString({ days: -120, hours: 15 }),
      worker: { connect: { id: 3 } },
      workplace: { connect: { id: 14 } },
      shard: 1,
  },
  {
      startAt: getRelativeDateString({ days: -115, hours: 15 }),
      endAt: getRelativeDateString({ days: -115, hours: 23 }),
      worker: { connect: { id: 8 } },
      workplace: { connect: { id: 14 } },
  },
  {
      startAt: getRelativeDateString({ days: -111, hours: 7 }),
      endAt: getRelativeDateString({ days: -111, hours: 15 }),
      worker: { connect: { id: 6 } },
      workplace: { connect: { id: 14 } },
  },
  {
      startAt: getRelativeDateString({ days: -110, hours: 7 }),
      endAt: getRelativeDateString({ days: -110, hours: 15 }),
      worker: { connect: { id: 6 } },
      workplace: { connect: { id: 14 } },
      shard: 1,
  },
  {
      startAt: getRelativeDateString({ days: -110, hours: 23 }),
      endAt: getRelativeDateString({ days: -109, hours: 7 }),
      worker: { connect: { id: 12 } },
      workplace: { connect: { id: 14 } },
      shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -108, hours: 7 }),
    endAt: getRelativeDateString({ days: -108, hours: 15 }),
    worker: { connect: { id: 6 } },
    workplace: { connect: { id: 14 } },
  },
  {
    startAt: getRelativeDateString({ days: -107, hours: 7 }),
    endAt: getRelativeDateString({ days: -107, hours: 15 }),
    worker: { connect: { id: 6 } },
    workplace: { connect: { id: 14 } },
  },
  {
      startAt: getRelativeDateString({ days: -105, hours: 7 }),
      endAt: getRelativeDateString({ days: -105, hours: 15 }),
      worker: { connect: { id: 5 } },
      workplace: { connect: { id: 14 } },
      shard: 1,
  },
  {
      startAt: getRelativeDateString({ days: -100, hours: 15 }),
      endAt: getRelativeDateString({ days: -100, hours: 23 }),
      worker: { connect: { id: 15 } },
      workplace: { connect: { id: 14 } },
      shard: 1,
  },
  {
      startAt: getRelativeDateString({ days: -95, hours: 23 }),
      endAt: getRelativeDateString({ days: -94, hours: 7 }),
      worker: { connect: { id: 1 } },
      workplace: { connect: { id: 9 } },
      shard: 1,
  },
  {
      startAt: getRelativeDateString({ days: -93, hours: 7 }),
      endAt: getRelativeDateString({ days: -92, hours: 15 }),
      worker: { connect: { id: 10 } },
      workplace: { connect: { id: 18 } },
      shard: 1
  }, 
  {
      startAt: getRelativeDateString({ days: -90, hours: 7 }),
      endAt: getRelativeDateString({ days: -90, hours: 15 }),
      worker: { connect: { id: 10 } },
      workplace: { connect: { id: 4 } },
      shard: 1,
  },
  {
      startAt: getRelativeDateString({ days: -85, hours: 15 }),
      endAt: getRelativeDateString({ days: -85, hours: 23 }),
      worker: { connect: { id: 6 } },
      workplace: { connect: { id: 13 } },
      shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -120, hours: 7 }),
    endAt: getRelativeDateString({ days: -120, hours: 15 }),
    worker: { connect: { id: 3 } },
    workplace: { connect: { id: 14 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -115, hours: 15 }),
    endAt: getRelativeDateString({ days: -115, hours: 23 }),
    worker: { connect: { id: 8 } },
    workplace: { connect: { id: 14 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -113, hours: 7 }),
    endAt: getRelativeDateString({ days: -112, hours: 15 }),
    worker: { connect: { id: 7 } },
    workplace: { connect: { id: 18 } },
  }, 
  {
    startAt: getRelativeDateString({ days: -111, hours: 7 }),
    endAt: getRelativeDateString({ days: -111, hours: 15 }),
    worker: { connect: { id: 6 } },
    workplace: { connect: { id: 14 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -110, hours: 7 }),
    endAt: getRelativeDateString({ days: -110, hours: 15 }),
    worker: { connect: { id: 18 } },
    workplace: { connect: { id: 14 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -110, hours: 23 }),
    endAt: getRelativeDateString({ days: -109, hours: 7 }),
    worker: { connect: { id: 12 } },
    workplace: { connect: { id: 14 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -125, hours: 7 }),
    endAt: getRelativeDateString({ days: -125, hours: 15 }),
    worker: { connect: { id: 5 } },
    workplace: { connect: { id: 14 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -124, hours: 15 }),
    endAt: getRelativeDateString({ days: -124, hours: 23 }),
    worker: { connect: { id: 15 } },
    workplace: { connect: { id: 14 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -123, hours: 23 }),
    endAt: getRelativeDateString({ days: -122, hours: 7 }),
    worker: { connect: { id: 1 } },
    workplace: { connect: { id: 9 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -122, hours: 7 }),
    endAt: getRelativeDateString({ days: -122, hours: 15 }),
    worker: { connect: { id: 10 } },
    workplace: { connect: { id: 4 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -121, hours: 15 }),
    endAt: getRelativeDateString({ days: -121, hours: 23 }),
    worker: { connect: { id: 6 } },
    workplace: { connect: { id: 13 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -120, hours: 7 }),
    endAt: getRelativeDateString({ days: -120, hours: 15 }),
    worker: { connect: { id: 3 } },
    workplace: { connect: { id: 14 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -115, hours: 15 }),
    endAt: getRelativeDateString({ days: -115, hours: 23 }),
    worker: { connect: { id: 8 } },
    workplace: { connect: { id: 14 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -114, hours: 7 }),
    endAt: getRelativeDateString({ days: -112, hours: 15 }),
    worker: { connect: { id: 10 } },
    workplace: { connect: { id: 4 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -111, hours: 7 }),
    endAt: getRelativeDateString({ days: -111, hours: 15 }),
    worker: { connect: { id: 6 } },
    workplace: { connect: { id: 14 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -111, hours: 7 }),
    endAt: getRelativeDateString({ days: -110, hours: 15 }),
    worker: { connect: { id: 16 } },
    workplace: { connect: { id: 18 } },
    shard: 1,
  }, 
  {
    startAt: getRelativeDateString({ days: -110, hours: 7 }),
    endAt: getRelativeDateString({ days: -110, hours: 15 }),
    worker: { connect: { id: 6 } },
    workplace: { connect: { id: 14 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -110, hours: 23 }),
    endAt: getRelativeDateString({ days: -109, hours: 7 }),
    worker: { connect: { id: 12 } },
    workplace: { connect: { id: 14 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -105, hours: 7 }),
    endAt: getRelativeDateString({ days: -105, hours: 15 }),
    worker: { connect: { id: 5 } },
    workplace: { connect: { id: 14 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -103, hours: 7 }),
    endAt: getRelativeDateString({ days: -101, hours: 15 }),
    worker: { connect: { id: 8 } },
    workplace: { connect: { id: 4 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -100, hours: 15 }),
    endAt: getRelativeDateString({ days: -100, hours: 23 }),
    worker: { connect: { id: 15 } },
    workplace: { connect: { id: 14 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -100, hours: 7 }),
    endAt: getRelativeDateString({ days: -100, hours: 15 }),
    worker: { connect: { id: 5 } },
    workplace: { connect: { id: 18 } },
  },
  {
    startAt: getRelativeDateString({ days: -98, hours: 15 }),
    endAt: getRelativeDateString({ days: -96, hours: 23 }),
    worker: { connect: { id: 5 } },
    workplace: { connect: { id: 4 } },
  },
  {
    startAt: getRelativeDateString({ days: -95, hours: 23 }),
    endAt: getRelativeDateString({ days: -94, hours: 7 }),
    worker: { connect: { id: 1 } },
    workplace: { connect: { id: 9 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -90, hours: 7 }),
    endAt: getRelativeDateString({ days: -90, hours: 15 }),
    worker: { connect: { id: 10 } },
    workplace: { connect: { id: 4 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -89, hours: 7 }),
    endAt: getRelativeDateString({ days: -87, hours: 15 }),
    worker: { connect: { id: 5 } },
    workplace: { connect: { id: 18 } },
  }, 
  {
    startAt: getRelativeDateString({ days: -85, hours: 15 }),
    endAt: getRelativeDateString({ days: -85, hours: 23 }),
    worker: { connect: { id: 6 } },
    workplace: { connect: { id: 13 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -82, hours: 23 }),
    endAt: getRelativeDateString({ days: -81, hours: 7 }),
    worker: { connect: { id: 10 } },
    workplace: { connect: { id: 2 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -80, hours: 23 }),
    endAt: getRelativeDateString({ days: -79, hours: 7 }),
    worker: { connect: { id: 14 } },
    workplace: { connect: { id: 1 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -79, hours: 15 }),
    endAt: getRelativeDateString({ days: -77, hours: 23 }),
    worker: { connect: { id: 7 } },
    workplace: { connect: { id: 4 } },
  },
  {
    startAt: getRelativeDateString({ days: -78, hours: 15 }),
    endAt: getRelativeDateString({ days: -76, hours: 23 }),
    worker: { connect: { id: 13 } },
    workplace: { connect: { id: 4 } },
  },
  {
    startAt: getRelativeDateString({ days: -76, hours: 15 }),
    endAt: getRelativeDateString({ days: -76, hours: 23 }),
    worker: { connect: { id: 9 } },
    workplace: { connect: { id: 3 } },
  },
  {
    startAt: getRelativeDateString({ days: -75, hours: 7 }),
    endAt: getRelativeDateString({ days: -75, hours: 15 }),
    worker: { connect: { id: 2 } },
    workplace: { connect: { id: 10 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -70, hours: 15 }),
    endAt: getRelativeDateString({ days: -70, hours: 23 }),
    worker: { connect: { id: 11 } },
    workplace: { connect: { id: 6 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -68, hours: 15 }),
    endAt: getRelativeDateString({ days: -66, hours: 23 }),
    worker: { connect: { id: 3 } },
    workplace: { connect: { id: 4 } },
  },
  {
    startAt: getRelativeDateString({ days: -65, hours: 23 }),
    endAt: getRelativeDateString({ days: -64, hours: 7 }),
    worker: { connect: { id: 7 } },
    workplace: { connect: { id: 14 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -60, hours: 7 }),
    endAt: getRelativeDateString({ days: -60, hours: 15 }),
    worker: { connect: { id: 13 } },
    workplace: { connect: { id: 8 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -60, hours: 23 }),
    endAt: getRelativeDateString({ days: -59, hours: 7 }),
    workplace: { connect: { id: 4 } },
  },
  {
    startAt: getRelativeDateString({ days: -58, hours: 7 }),
    endAt: getRelativeDateString({ days: -56, hours: 15 }),
    worker: { connect: { id: 20 } },
    workplace: { connect: { id: 18 } },
  }, 
  {
    startAt: getRelativeDateString({ days: -55, hours: 15 }),
    endAt: getRelativeDateString({ days: -55, hours: 23 }),
    worker: { connect: { id: 4 } },
    workplace: { connect: { id: 12 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -52, hours: 15 }),
    endAt: getRelativeDateString({ days: -50, hours: 23 }),
    worker: { connect: { id: 8 } },
    workplace: { connect: { id: 4 } },
  },
  {
    startAt: getRelativeDateString({ days: -50, hours: 23 }),
    endAt: getRelativeDateString({ days: -49, hours: 7 }),
    worker: { connect: { id: 9 } },
    workplace: { connect: { id: 15 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -48, hours: 15 }),
    endAt: getRelativeDateString({ days: -48, hours: 23 }),
    worker: { connect: { id: 8 } },
    workplace: { connect: { id: 1 } },
  },
  {
    startAt: getRelativeDateString({ days: -43, hours: 15 }),
    endAt: getRelativeDateString({ days: -43, hours: 23 }),
    worker: { connect: { id: 3 } },
    workplace: { connect: { id: 4 } },
  },
  {
    startAt: getRelativeDateString({ days: -25, hours: 23 }),
    endAt: getRelativeDateString({ days: -24, hours: 7 }),
    worker: { connect: { id: 5 } },
    workplace: { connect: { id: 13 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -24, hours: 7 }),
    endAt: getRelativeDateString({ days: -24, hours: 15 }),
    worker: { connect: { id: 2 } },
    workplace: { connect: { id: 5 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -21, hours: 7 }),
    endAt: getRelativeDateString({ days: -21, hours: 15 }),
    workplace: { connect: { id: 4 } },
  },
  {
    startAt: getRelativeDateString({ days: -19, hours: 23 }),
    endAt: getRelativeDateString({ days: -18, hours: 7 }),
    worker: { connect: { id: 4 } },
    workplace: { connect: { id: 2 } },
  },
  {
    startAt: getRelativeDateString({ days: -17, hours: 7 }),
    endAt: getRelativeDateString({ days: -17, hours: 15 }),
    worker: { connect: { id: 1 } },
    workplace: { connect: { id: 3 } },
  },
  {
    startAt: getRelativeDateString({ days: -17, hours: 7 }),
    endAt: getRelativeDateString({ days: -16, hours: 15 }),
    worker: { connect: { id: 10 } },
    workplace: { connect: { id: 4 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -16, hours: 7 }),
    endAt: getRelativeDateString({ days: -16, hours: 15 }),
    worker: { connect: { id: 2 } },
    workplace: { connect: { id: 1 } },
  },
  {
    startAt: getRelativeDateString({ days: -15, hours: 7 }),
    endAt: getRelativeDateString({ days: -15, hours: 15 }),
    workplace: { connect: { id: 2 } },
  },
  {
    startAt: getRelativeDateString({ days: -14, hours: 7 }),
    endAt: getRelativeDateString({ days: -14, hours: 15 }),
    worker: { connect: { id: 12 } },
    workplace: { connect: { id: 11 } },
  },
  {
    startAt: getRelativeDateString({ days: -14, hours: 15 }),
    endAt: getRelativeDateString({ days: -14, hours: 23 }),
    worker: { connect: { id: 12 } },
    workplace: { connect: { id: 11 } },
  },
  {
    startAt: getRelativeDateString({ days: -13, hours: 7 }),
    endAt: getRelativeDateString({ days: -13, hours: 15 }),
    worker: { connect: { id: 12 } },
    workplace: { connect: { id: 11 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -12, hours: 15 }),
    endAt: getRelativeDateString({ days: -12, hours: 23 }),
    worker: { connect: { id: 12 } },
    workplace: { connect: { id: 11 } },
  },
  {
    startAt: getRelativeDateString({ days: -12, hours: 15 }),
    endAt: getRelativeDateString({ days: -12, hours: 23 }),
    worker: { connect: { id: 10 } },
    workplace: { connect: { id: 11 } },
  },
  {
    startAt: getRelativeDateString({ days: -12, hours: 7 }),
    endAt: getRelativeDateString({ days: -12, hours: 15 }),
    workplace: { connect: { id: 5 } },
  },
  {
    startAt: getRelativeDateString({ days: -11, hours: 7 }),
    endAt: getRelativeDateString({ days: -11, hours: 15 }),
    worker: { connect: { id: 7 } },
    workplace: { connect: { id: 14 } },
  },
  {
    startAt: getRelativeDateString({ days: -10, hours: 7 }),
    endAt: getRelativeDateString({ days: -10, hours: 15 }),
    worker: { connect: { id: 8 } },
    workplace: { connect: { id: 14 } },
  },
  {
    startAt: getRelativeDateString({ days: -9, hours: 7 }),
    endAt: getRelativeDateString({ days: -9, hours: 15 }),
    workplace: { connect: { id: 14 } },
  },
  {
    startAt: getRelativeDateString({ days: -8, hours: 7 }),
    endAt: getRelativeDateString({ days: -8, hours: 15 }),
    worker: { connect: { id: 11 } },
    workplace: { connect: { id: 11 } },
  },
  {
    startAt: getRelativeDateString({ days: -8, hours: 7 }),
    endAt: getRelativeDateString({ days: -8, hours: 15 }),
    workplace: { connect: { id: 15 } },
  },
  {
    startAt: getRelativeDateString({ days: -7, hours: 7 }),
    endAt: getRelativeDateString({ days: -7, hours: 15 }),
    workplace: { connect: { id: 14 } },
  },
  {
    startAt: getRelativeDateString({ days: -7, hours: 15 }),
    endAt: getRelativeDateString({ days: -7, hours: 23 }),
    workplace: { connect: { id: 14 } },
  },
  {
    startAt: getRelativeDateString({ days: -6, hours: 7 }),
    endAt: getRelativeDateString({ days: -6, hours: 15 }),
    worker: { connect: { id: 2 } },
    workplace: { connect: { id: 11 } }
  },
  {
    startAt: getRelativeDateString({ days: -5, hours: 7 }),
    endAt: getRelativeDateString({ days: -5, hours: 15 }),
    worker: { connect: { id: 2 } },
    workplace: { connect: { id: 11 } }
  },
  {
    startAt: getRelativeDateString({ days: -6, hours: 7 }),
    endAt: getRelativeDateString({ days: -6, hours: 15 }),
    worker: { connect: { id: 3 } },
    workplace: { connect: { id: 18 } },
  },
  {
    startAt: getRelativeDateString({ days: -6, hours: 15 }),
    endAt: getRelativeDateString({ days: -6, hours: 23 }),
    worker: { connect: { id: 4 } },
    workplace: { connect: { id: 18 } },
  },
  {
    startAt: getRelativeDateString({ days: -5, hours: 7 }),
    endAt: getRelativeDateString({ days: -5, hours: 15 }),
    worker: { connect: { id: 3 } },
    workplace: { connect: { id: 18 } },
  },
  {
    startAt: getRelativeDateString({ days: -4, hours: 7 }),
    endAt: getRelativeDateString({ days: -4, hours: 15 }),
    worker: { connect: { id: 4 } },
    workplace: { connect: { id: 18 } },
  },
  {
    startAt: getRelativeDateString({ days: -3, hours: 7 }),
    endAt: getRelativeDateString({ days: -3, hours: 15 }),
    worker: { connect: { id: 5 } },
    workplace: { connect: { id: 18 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -2, hours: 7 }),
    endAt: getRelativeDateString({ days: -2, hours: 15 }),
    worker: { connect: { id: 6 } },
    workplace: { connect: { id: 18 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: -1, hours: 7 }),
    endAt: getRelativeDateString({ days: -1, hours: 15 }),
    worker: { connect: { id: 7 } },
    workplace: { connect: { id: 18 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: 0, hours: 7 }),
    endAt: getRelativeDateString({ days: 0, hours: 15 }),
    workplace: { connect: { id: 18 } },
  },
  {
    startAt: getRelativeDateString({ days: 1, hours: 7 }),
    endAt: getRelativeDateString({ days: 1, hours: 15 }),
    worker: { connect: { id: 9 } },
    workplace: { connect: { id: 3 } },
  },
  {
    startAt: getRelativeDateString({ days: 2, hours: 7 }),
    endAt: getRelativeDateString({ days: 2, hours: 15 }),
    worker: { connect: { id: 10 } },
    workplace: { connect: { id: 4 } },
  },
  {
    startAt: getRelativeDateString({ days: 3, hours: 7 }),
    endAt: getRelativeDateString({ days: 3, hours: 15 }),
    worker: { connect: { id: 11 } },
    workplace: { connect: { id: 5 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: 3, hours: 7 }),
    endAt: getRelativeDateString({ days: 3, hours: 15 }),
    worker: { connect: { id: 11 } },
    workplace: { connect: { id: 5 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: 4, hours: 7 }),
    endAt: getRelativeDateString({ days: 4, hours: 15 }),
    worker: { connect: { id: 12 } },
    workplace: { connect: { id: 6 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: 4, hours: 15 }),
    endAt: getRelativeDateString({ days: 4, hours: 23 }),
    worker: { connect: { id: 12 } },
    workplace: { connect: { id: 6 } },
  },
  {
    startAt: getRelativeDateString({ days: 5, hours: 7 }),
    endAt: getRelativeDateString({ days: 5, hours: 15 }),
    worker: { connect: { id: 13 } },
    workplace: { connect: { id: 7 } },
  },
  {
    startAt: getRelativeDateString({ days: 5, hours: 23 }),
    endAt: getRelativeDateString({ days: 6, hours: 7 }),
    workplace: { connect: { id: 7 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: 6, hours: 7 }),
    endAt: getRelativeDateString({ days: 6, hours: 15 }),
    worker: { connect: { id: 14 } },
    workplace: { connect: { id: 8 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: 6, hours: 7 }),
    endAt: getRelativeDateString({ days: 6, hours: 15 }),
    worker: { connect: { id: 14 } },
    workplace: { connect: { id: 8 } },
  },
  {
    startAt: getRelativeDateString({ days: 7, hours: 15 }),
    endAt: getRelativeDateString({ days: 7, hours: 23 }),
    worker: { connect: { id: 15 } },
    workplace: { connect: { id: 9 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: 8, hours: 23 }),
    endAt: getRelativeDateString({ days: 9, hours: 7 }),
    worker: { connect: { id: 16 } },
    workplace: { connect: { id: 10 } },
  },
  {
    startAt: getRelativeDateString({ days: 9, hours: 7 }),
    endAt: getRelativeDateString({ days: 9, hours: 15 }),
    workplace: { connect: { id: 11 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: 10, hours: 15 }),
    endAt: getRelativeDateString({ days: 10, hours: 23 }),
    worker: { connect: { id: 18 } },
    workplace: { connect: { id: 12 } },
  },
  {
    startAt: getRelativeDateString({ days: 11, hours: 23 }),
    endAt: getRelativeDateString({ days: 12, hours: 7 }),
    worker: { connect: { id: 19 } },
    workplace: { connect: { id: 13 } },
    shard: 1,
  },
  {
    startAt: getRelativeDateString({ days: 12, hours: 7 }),
    endAt: getRelativeDateString({ days: 12, hours: 15 }),
    worker: { connect: { id: 20 } },
    workplace: { connect: { id: 14 } },
  },
];
